# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
# llm:
#   api_type: "openai"  # or azure / ollama / groq etc.
#   model: "gpt-4-turbo"  # or gpt-3.5-turbo
#   base_url: "https://api.openai.com/v1"  # or forward url / other llm url
#   api_key: "YOUR_API_KEY"

# llm:
#   api_type: 'qianfan'
#   access_key: '"YOUR_API_KEY"'
#   secret_key: '"YOUR_API_KEY"'
#   model: 'ernie-speed-128k'

# llm:
#   api_type: 'spark'
#   app_id: '36240d7d'
#   api_key: '"YOUR_API_KEY"'
#   api_secret: '"YOUR_API_KEY"'
#   domain: 'lite'
#   base_url: 'wss://spark-api.xf-yun.com/v1.1/chat'


# llm:
#   api_type: 'zhipuai'
#   api_key: '"YOUR_API_KEY"'
#   model: 'glm-4-flash'


# llm:
#   api_type: "openai"  
#   model: "ernie-speed-128k"
#   base_url: 'https://qianfan.baidubce.com/v2'
#   api_key: '"YOUR_API_KEY"'
#   temperature: '0.3'

# llm:
#   api_type: "openai"  
#   model: "deepseek-v3.2"
#   base_url: 'https://qianfan.baidubce.com/v2'
#   api_key: '"YOUR_API_KEY"'
#   temperature: '0.3'


llm:
  api_type: "openai"  
  model: "deepseek-chat"
  base_url: 'https://api.deepseek.com'
  api_key: '"YOUR_API_KEY"'

# llm:
#   api_type: "openai"  
#   model: "deepseek-reasoner "
#   base_url: 'https://api.deepseek.com'
#   api_key: '"YOUR_API_KEY"'

# search:
#   api_type: 'ddg' # serpapi/google/serper/ddg

search:
  api_type: 'serper' 
  api_key: '"YOUR_API_KEY"'

browser:
  engine: "selenium"  # playwright/selenium
  browser_type: "chrome"  # playwright: chromium/firefox/webkit; selenium: chrome/firefox/edge/ie
